#!/usr/bin/env bash
set -euo pipefail

source_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

die() {
  printf 'copier update check error: %s\n' "$*" >&2
  exit 1
}

[[ "${1:-}" == "--target" && "$#" -eq 2 ]] || die "usage: $0 --target DIR"
target="$2"
[[ -d "$target" ]] || die "target missing: $target"

copier_bin="$(command -v copier || true)"
[[ -n "$copier_bin" ]] || die "copier not found"
copier_version="$("$copier_bin" --version 2>&1)" || die "unable to read Copier version"
[[ "$copier_version" == "copier 9.17.1" ]] || die "Copier version mismatch: expected copier 9.17.1, got $copier_version"

canonical="$target/.agents/skills/copier-conflict-fixture/SKILL.md"
generated="$target/.claude/skills/copier-conflict-fixture/SKILL.md"
allowed_reject="$target/.claude/skills/copier-conflict-fixture/SKILL.md.rej"
project_owned="$target/.agents/skills/project-owned/SKILL.md"
skip_state="$target/context/WORKING.md"

[[ -f "$canonical" && ! -L "$canonical" ]] || die "unexpected Copier outcome: canonical source missing or wrong class"
[[ -f "$generated" && ! -L "$generated" ]] || die "unexpected Copier outcome: generated projection missing or wrong class"
[[ -f "$project_owned" && -f "$skip_state" ]] || die "project-owned or skip state fixture missing"
project_hash_before="$(sha256sum "$project_owned" | awk '{print $1}')"
skip_hash_before="$(sha256sum "$skip_state" | awk '{print $1}')"

receipt_dir="$(mktemp -d)"
trap 'rm -rf "$receipt_dir"' EXIT
set +e
"$copier_bin" update --defaults --trust "$target" >"$receipt_dir/copier.stdout" 2>"$receipt_dir/copier.stderr"
copier_status=$?
set -e
[[ "$copier_status" -eq 0 ]] || die "Copier exited $copier_status; stdout/stderr recorded"

[[ -f "$canonical" && ! -L "$canonical" ]] || die "canonical ownership breach: unexpected Copier outcome"
[[ -f "$generated" && ! -L "$generated" ]] || die "unexpected Copier outcome: generated projection missing"

if grep -Eq '^(<<<<<<<|=======|>>>>>>>)' "$canonical"; then
  die "canonical ownership conflict: unexpected Copier outcome"
fi

mapfile -t artifacts < <(find "$target" -type f \( -name '*.rej' -o -name '*.orig' \) -print | LC_ALL=C sort)
for artifact_path in "${artifacts[@]}"; do
  [[ "$artifact_path" == "$allowed_reject" ]] || die "unexpected Copier artifact: $artifact_path"
done

marker_open="$(grep -c '^<<<<<<<' "$generated" || true)"
marker_middle="$(grep -c '^=======' "$generated" || true)"
marker_close="$(grep -c '^>>>>>>>' "$generated" || true)"
classification=""
if [[ -f "$allowed_reject" ]]; then
  classification="reject-artifact"
elif [[ "$marker_open" -gt 0 && "$marker_middle" -gt 0 && "$marker_close" -gt 0 ]]; then
  classification="conflict-markers"
elif [[ "$marker_open" -ne 0 || "$marker_middle" -ne 0 || "$marker_close" -ne 0 ]]; then
  die "partial marker set: unexpected Copier outcome"
elif cmp -s "$canonical" "$generated"; then
  classification="clean-overwrite"
else
  die "unexpected Copier outcome: generated bytes are neither clean nor conflicted"
fi

if [[ "$classification" == "reject-artifact" ]]; then
  rm -- "$allowed_reject"
fi

python3 "$source_root/scripts/generate-skill-surfaces.py" --project-root "$target"
python3 "$source_root/scripts/generate-skill-surfaces.py" --project-root "$target" --check
python3 "$source_root/scripts/ci/check-skill-routes.py" --project-root "$target"

cmp -s "$canonical" "$generated" || die "generated projection differs from canonical after remediation"
if grep -REq '^(<<<<<<<|=======|>>>>>>>)' "$target/.claude/skills"; then
  die "conflict marker remains after remediation"
fi
if find "$target" -type f \( -name '*.rej' -o -name '*.orig' \) -print -quit | grep -q .; then
  die "unexpected reject/original artifact remains"
fi
project_hash_after="$(sha256sum "$project_owned" | awk '{print $1}')"
skip_hash_after="$(sha256sum "$skip_state" | awk '{print $1}')"
[[ "$project_hash_before" == "$project_hash_after" ]] || die "project-owned hash drift"
[[ "$skip_hash_before" == "$skip_hash_after" ]] || die "skip state hash drift"

printf 'copier update check: PASS classification=%s version=%s status=%s\n' "$classification" "$copier_version" "$copier_status"
